# Generated by Django 2.0.2 on 2018-03-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgame', '0002_auto_20180305_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='won',
            field=models.IntegerField(null=True),
        ),
    ]
